### ISSUE TITLE
Error 401 

### ISSUE THREAD

**Issue by WILLISsteve** [aerouk/imageserve#11]
I entered everything in this picture found on the wiki page (https://camo.githubusercontent.com/5d6300a55c1118163d18f509d13a4828fc6563fe/687474703a2f2f696165726f2e6d652f692f4d75507841), but when I test the image uploader i'm left with "URL: https://i.speed.wtf/e-401". Not sure what other things I need to show you, but I followed the video and this is all i'm getting. Any way to fix this?

**Comment by aerouk** [comment]
Error 401 means you entered the wrong password. I'd re-check that you're entering the same password as in your config file.

**Comment by WILLISsteve** [comment]
Ah, that did it. For some reason the file didn't save when I uploaded it to the FTP. Thanks!
