### ISSUE TITLE
please enable Javascript in your browser or use a browser with Javascript support< error with custom uploader?

### ISSUE THREAD

**Issue by Spikechrisgaming** [aerouk/imageserve#13]
So i was trying to use a custom uploader and such and i'm getting this error 

```
please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>
```
How do i fix this?

My default browser has javascript enabled and my other browsers i have installed.

**Comment by aerouk** [comment]
Where are you getting this error? Imageserve doesn't use any js.

**Comment by Spikechrisgaming** [comment]
Just on the ShareX window it gives me my url and then that error.

I posted this on the ShareX github also and they just said i had to fix my site.

**Comment by Spikechrisgaming** [comment]
They also said this 

```
Probably that place you trying to upload checks User-Agent which is ShareX and thinks that browser not supports javascript.
```

**Comment by addles** [comment]
can I see a picture of your settings? don't forget to remove sensitive pieces like the password

**Comment by Spikechrisgaming** [comment]
http://i.imgur.com/qWXcbSm.jpg

**Comment by Spikechrisgaming** [comment]
Don't mind the /s in there just something i forgot to change but still does the same thing.

**Comment by aerouk** [comment]
There's some kind of protection on your website that injects javascript to check the browser. You need to find out how to remove this otherwise it won't be able to be loaded without javascript.

![](https://iaero.me/i/XnsS7)

**Comment by Spikechrisgaming** [comment]
Well i got it to work.. is there a way to maybe let others upload there? like having other passwords?

**Comment by aerouk** [comment]
Not currently. I'll add multi-user support to the ideas list.

If you find any additional issues, please don't hesitate to open a new issue.
