### ISSUE TITLE
404 error? 

### ISSUE THREAD

**Issue by policies** [aerouk/imageserve#15]
I'm a huge noob.

I put imageserve into a folder named 'imageserve-demo'. This is what happens when I use the test button on ShareX: http://i.william.sh/imageserve-demo/wY4xg

I get a 404 error. I have a feeling this is a very simple fix, and that I am just either a huge noob, or just really tired.

My /images is set to 0777 in WinSCP.

I can provide any files (such as my config.php) if needed.

Thank you! I would like to get this resolved as soon as possible. :+1:

**Comment by aerouk** [comment]
You need to allow .htaccess files to overwrite the main apache config.

---

In your `httpd.conf` file, you need to add `AllowOverride All` to the directory config. If you don't get what I'm saying, there's a good example [here](http://askubuntu.com/a/429931).

After you've done that, just restart apache and you should be good to go.

**Comment by policies** [comment]
Where is httpd.conf located? I am on Ubuntu 14.04

**Comment by aerouk** [comment]
Depends what kind of setup you're running. Do you have different sites configured individually or in one file? 

..or are you using the default www directory?...

**Comment by policies** [comment]
My stuff is in /var/www/html

**Comment by aerouk** [comment]
It's probably `/etc/apache2/sites-available/default` but I've never used ubuntu so I can't be sure. If you don't understand what you're doing with apache, it's probably best just to google it..

**Comment by policies** [comment]
Is it default-ssl.conf?

**Comment by aerouk** [comment]
Hold on, I'll spin up an apache server to see wtf you're on about.

**Comment by aerouk** [comment]
`/etc/apache2/sites-enabled/000-default.conf` - you got this file?

Add a `<Directory>` directive inside the virtualhost for your main web directory as such: (replace imageserve-demo when you come to rename the directory)

```
<Directory "/var/www/html/imageserve-demo">
    Options -Indexes
    AllowOverride All
</Directory>

**Comment by policies** [comment]
So like this? https://william.cx/i/4SZo.png

http://i.william.sh/imageserve-demo/N2xkR - still getting a 404. :/

**Comment by aerouk** [comment]
Restarted apache?

**Comment by policies** [comment]
I did that and now I'm getting "Internal Server Error"

see here: http://i.william.sh/imageserve-demo/N2xkR

..sorry to continue bothering you...

**Comment by aerouk** [comment]
Dunno what to tell you. I don't want to sound rude but I'm not here to troubleshoot your apache problems. If I were you I'd do some googling.

**Comment by iCake** [comment]
banter

**Comment by addles** [comment]
I would say start over with a fresh VM and install a web panel like cpanel
or vestacp

**Comment by policies** [comment]
I'll try installing cPanel, but how will that make it different?

**Comment by addles** [comment]
It would make it easier to change settings with apache.
