### ISSUE TITLE
Append file extension to hashed URL (toggleable)

### ISSUE THREAD

**Issue by Arcaenist** [aerouk/imageserve#17]
I'm the one who emailed you about the image extension being appended to the raw image link by default. You told me to make an issue and here it is. :+1:

**Comment by aerouk** [comment]
Support for this added in the new [**stable release**](https://github.com/aerouk/imageserve/releases/tag/0.0.4-stable)!

Thanks for the suggestion. I planned to add this ages ago but like other things I just didn't get round to doing it. :)

**Comment by Arcaenist** [comment]
That was fast. :D
