### ISSUE TITLE
.htaccess not working?

### ISSUE THREAD

**Issue by wmbtc** [aerouk/imageserve#18]
Hey,

It seems as if my .htaccess file is not doing anything, when I go to the direct file path it works just fine (http://website.com/images/png/image.png/) but when I go to http://website.com/image/ it does nothing and just says "Not Found".

Do you know what might be wrong? Thanks!

I have set the permissions on /images/ and .htaccess to 777.

Does anyone have a fix for this? Thanks!

**Comment by aerouk** [comment]
Do you have `AllowOverride All` set in your apache config?

**Comment by wmbtc** [comment]
Yeah, all 4 options of "AllowOverride" are set to "All" in /etc/apache2/apache2.conf

Is that what you're talking about?

Thanks for the quick reply.

**Comment by wmbtc** [comment]
EDIT: After restarting apache it worked!

Silly me. Thank you for the help!
