### ISSUE TITLE
Files uploading but no image

### ISSUE THREAD

**Issue by fireshaper** [aerouk/imageserve#20]
I've set up your script on a server running PHP 5.6. I get success returned to ShareX but when I try to go to the image there's nothing there. I've checked the images directory and there's nothing in there either. All of the directories are set to 777.

**Comment by aerouk** [comment]
Works fine for me as of 5237716c19511c2a29d9e46b1f19c7151b74d0d6, can you try again?

**Comment by fireshaper** [comment]
I found out what was going on with the images not uploading, but when I follow your instructions to configure ShareX it seems like there's something missing to get the full path. The image uploads but ShareX returns the address http://domian.tld/image_name, which isn't a valid path.

**Comment by aerouk** [comment]
Did you follow the video instructions? That shouldn't happen

**Comment by fireshaper** [comment]
Yes, I did. It's like you are missing a regex value. I tested on my machine and also on another server that a friend set up. We had to change the config to use the full https://domain.tld/imageserve/images/png/image.png.

**Comment by aerouk** [comment]
The regex is correct. You need to change a config value if you're not using the default directory. I probably should have specified in the video, my bad

**Comment by aerouk** [comment]
@fireshaper Any update on this? It's been a few months and the issue still isn't resolved.

**Comment by fireshaper** [comment]
@aerouk It's working, but had to make some changes on my side to resolve it. I'm uploading straight to the png folder, but all I use is png anyway, so it's not a big deal.

**Comment by aerouk** [comment]
I can't figure out why you couldn't get the upload script to work. I haven't seen anyone else with this issue.
