### ISSUE TITLE
Remove j/g from raw image link

### ISSUE THREAD

**Issue by Arcaenist** [aerouk/imageserve#25]
Hi there. I'm @aspiegeek on Twitter and I wasn't sure how to make a pull request (tells me there's nothing to compare and I don't have anything on here) and so this would work better imo. I'm also the one who suggested the raw image link suggestion from May.

Anyway, I'd like to suggest a way to remove the /j/ and /g/ from the raw image link so no matter what type of file it is, it'll always be domain.tld/abc123.xyz rather than /j/abc123.xyz or /g/abc123.xyz. I find it very annoying when I'm uploading and sharing with those two directories.

**Comment by aerouk** [comment]
Added support for this in 3d113ce817cdb68b30cda366da04e9ebb18e0e60. 

You need only download the updated `.htaccess` file if you were already running on the latest version since that's all that changed pretty much.
