### ISSUE TITLE
Support for other files?

### ISSUE THREAD

**Issue by demihypercube** [aerouk/imageserve#32]
Is it possible to have support for other files as well? Like zip or txt? That would be really useful.

**Comment by ApolloMason** [comment]
I can vouch for this, If I wanna upload a file such as a zip, I have to change my uploader. However if I wanna upload a webm, I gotta change it back

**Comment by demihypercube** [comment]
If the owner ever does this, maybe have a "Click to download" on the viewer for the zip page.

**Comment by aerouk** [comment]
This is an image uploading script.
