### ISSUE TITLE
WebM

### ISSUE THREAD

**Issue by victionn** [aerouk/imageserve#33]
I followed the steps exactly to use webm on my server, yet I just get this as the url 'https://i.theapollo.xyz/e-415'

I dont know whats happening, I copied the steps exactly, and my images work aswell

**Comment by addles** [comment]
Have you looked here? https://github.com/aerouk/imageserve/wiki/Error-Troubleshooting

Make sure that the file that ShareX is uploading is webm https://prtscr.io/gAg8X

**Comment by ApolloMason** [comment]
https://i.theapollo.xyz/qWr2w

**Comment by aerouk** [comment]
Is your server set up to accept large files?

**Comment by ApolloMason** [comment]
Yeah, it was working before. Then it just stopped working the next day, but my friend can do it yet I cant. We use the same web hosting.

**Comment by duramato** [comment]
I am also facing this issue. Files around 1MB work as ones with like 2MB don't

>Is your server set up to accept large files?

How i set that up on apache2?

**Comment by duramato** [comment]
Actually, this did the trick for me: https://stackoverflow.com/a/27883689

**Comment by aerouk** [comment]
Closing this since it seems to be a webserver issue, not of imageserve. Re-open if I'm wrong.
