### ISSUE TITLE
Can I Change This?

### ISSUE THREAD

**Issue by demihypercube** [aerouk/imageserve#34]
Can I remove the /w/, /g/, or /j/ from the url? Not the raw link, but this kind: https://demihypercube.space/i/g/4tCGS

**Comment by demihypercube** [comment]
Switched to a different program.

**Comment by aerouk** [comment]
? #25

**Comment by demihypercube** [comment]
[This](https://gist.github.com/demihypercube/6e7a2023007317e1b582c9acedd52452) is my .htaccess. I just removed the /j/g/w in the front and now it broke PNGs. Using .png  works, but removing it doesn't.

https://demihypercube.space/i/wPevr.png <-- Works.
https://demihypercube.space/i/wPevr <-- Doesn't work. 

I don't see why PNGs broke, I didn't change that line.

**Comment by aerouk** [comment]
Because now it doesn't know what type of image it's trying to find. Solution for your problem isn't implemented.
