### ISSUE TITLE
Add an easier way to delete all your pictures

### ISSUE THREAD

**Issue by bws35** [aerouk/imageserve#43]
If you add this line of code to your upload.php you can just delete the folder in the image folder.
And then it will make the png/gif/jpg folders by itself. I think you should really implement this :)

`if (!file_exists("/" . $dir . "/" . $type . "/")) {
        mkdir($dir . "/" . $type, 0777);
    }
`

**Comment by aerouk** [comment]
I don't think deleting all pictures is something you'd have to do often enough to warrant a change like this. Just go into each folder and delete all pictures.

If you want functionality like this, fork the project and make the change for your self.
