### ISSUE TITLE
viewer.php not found

### ISSUE THREAD

**Issue by DeefH** [aerouk/imageserve#44]
I everything works but when I try to look at the picture I get "The requested URL /viewer.php was not found on this server."
I have the viewer.php in the correct dir
![bae8cda44054f663286ec8be29c78155](https://user-images.githubusercontent.com/24248168/34507280-c8d789f4-f034-11e7-8096-9a5eac03823b.png)

url: http://daddy.putitin.me/mZ9BX

**Comment by addles** [comment]
Did you make sure that it has the right permissions?

**Comment by DeefH** [comment]
Yes, 777

**Comment by addles** [comment]
Do you have you. Htaccess file?

**Comment by DeefH** [comment]
Fixed it had something wrong in my sharex
