### ISSUE TITLE
The requested URL was not found on this server

### ISSUE THREAD

**Issue by Electricz1337** [aerouk/imageserve#46]
Hey,

it kinda looks like the viewer is fucked up. I can make Screenshots and I can test the image uploader, but it keeps saying that the requested URL wasnt found on the server.

However the Pictures itself get uploaded and can also be viewed with the complete URL.

Example:
Not working:
https://cleanlegen.de/i/FeK5D
Working:
https://cleanlegen.de/i/images/png/FeK5D.png

Any Idea how to fix?

Here are my Settings:
`<?php

//   _
//  (_)    A self-hosted ShareX image serving solution.
//   _ _ __ ___   __ _  __ _  ___  ___  ___ _ ____   _____
//  | | '_ ` _ \ / _` |/ _` |/ _ \/ __|/ _ \ '__\ \ / / _ \
//  | | | | | | | (_| | (_| |  __/\__ \  __/ |   \ V /  __/
//  |_|_| |_| |_|\__,_|\__, |\___||___/\___|_|    \_/ \___|
//                      __/ |
//                     |___/   created by github.com/aerouk

/* More information on all these values can be found on the wiki page. */
/* https://github.com/aerouk/imageserve/wiki/Configuration */

define('RAW_IMAGE', true);
define('RAW_IMAGE_LINK', false);
define('IMAGE_EXTENSION', false);

define('TWITTER_CARDS', false);

// If you're using this, make sure to put a forward slash before.
// E.g. "/imageserve" not "imageserve"
define('IMAGESERVE_DIR', '/i');
define('TWITTER_HANDLE', '@Electricz_y0');

define('APP_NAME', 'imageserve');
define('PASSKEY', 'dummerhurensohn124323bhj12nn');
`

ShareX:
https://cleanlegen.de/i/images/png/xdC7r.png

I am using cloudflare, but i dont think that this is the problem

Thanks in advance

**Comment by aerouk** [comment]
Assuming you're using Apache, make sure mod_rewrite is enabled and you have
overrides enabled in your site config.

**Comment by aerouk** [comment]
Closing as this seems abandoned. If somehow this still doesn't work please reopen.
