### ISSUE TITLE
Javascript issue

### ISSUE THREAD

**Issue by jtsshieh** [aerouk/imageserve#47]
I'm getting this error: https://i.imgur.com/jQQnKh6.png

I know for sure that all my info is correct. I'm using infinity host and my directory structure goes as follows: https://i.imgur.com/PGbVbu8.png

Not sure what is causing this but any help would be appreciated.

Thanks

**Comment by aerouk** [comment]
Can't remember if I fixed an issue like this before, but make sure there's
no firewall on your host blocking sharex from uploading

**Comment by jtsshieh** [comment]
Okay, I found out what happened. Apparently, infinity does not allow these type of programs to be hosted on their free servers.
