### ISSUE TITLE
ShareX 12.3 New Issue (Regex)

### ISSUE THREAD

**Issue by NicholasG04** [aerouk/imageserve#52]
Hi, just want to let you and others know that there has now been a change in how regex is used within ShareX, meaning that in the URL box of the custom uploader configuration it needs to be changed from:

http://yourwebsite.extension/$1$ to http://yourwebsite.extension/$regex:1$

Not doing this means that responses will show correctly, but they will be translated into urls that are simply http://yourwebsite.extension without a link to the image.

Thanks!

**Comment by D3XX3R1337** [comment]
Now I get
http://youtwebsite.tld/e-401

**Comment by SquidThePrinter** [comment]
The result now returns this for me:
`URL: https://yourwebsite.extension/home/user/public_html/images/png/image.png`

I'm bad at regex. Any ideas on what to do in this case?

**Comment by aerouk** [comment]
It's interesting this has been changed in ShareX and there wasn't any mention of it whatsoever. Thanks for pointing this out for my sanity also :+1:

**Comment by NicholasG04** [comment]
@aerouk it's not a problem, and the reason I found out was actually from the changeling since it was (obscurely) mentioned in there. Glad my little fix helped! 

Not honestly sure why they didn't make it clearer, or how it really helps for much at all on their part but it is what it is. Thankfully not exactly a bug fix.


Thanks for providing the software you do, I use it daily!

**Comment by Jaex** [comment]
> and there wasn't any mention of it whatsoever

I written it to changelog like this:

![](https://jaex.getsharex.com/2018/11/chrome_nN5XR9q9NX.png)

So how there is no mention for it?

**Comment by aerouk** [comment]
Poor choice of words on my part. I meant there was no mention of it when
updating ShareX with the built-in updater. Ideally it would have
automatically converted the regex in my custom uploaders but I can
appreciate the issues that may cause.

Thanks for providing some clarification on this

**Comment by mobbdeep** [comment]
I am receiving http://yoursite.tld/e-415. 

![Image of my settings](https://i.imgur.com/d01JJSV.png)

Any reason why?

**Comment by aerouk** [comment]
> 
> 
> I am receiving http://yoursite.tld/e-415.
> 
> (image redacted)
> 
> Any reason why?

Please refer to the [**Error Troubleshooting guide**](https://github.com/aerouk/imageserve/wiki/Error-Troubleshooting) for help with errors.

**Comment by mobbdeep** [comment]
> @mobbdeep
> 
> > I am receiving http://yoursite.tld/e-415.
> > (image redacted)
> > Any reason why?
> 
> Please refer to the [**Error Troubleshooting guide**](https://github.com/aerouk/imageserve/wiki/Error-Troubleshooting) for help with errors.

Those troubleshooting steps didn't work. I'm not understanding how the file is not being uploaded at all or even in an invalid format. I did nothing different from my original settings except change the regex thing since I updated ShareX the other day.

**Comment by aerouk** [comment]
@mobbdeep I'll do some testing later on today. I haven't had this issue
reported by any other users, though.

**Comment by mobbdeep** [comment]
I went ahead and completely redid the custom uploader information and I still get the same error. I don't know if it has to do with the use of SSL or anything like that but I still get the same error. I went as far as simplifying the password to 12 characters using letters and numbers only.

**Comment by NicholasG04** [comment]
Not SSL, since I use SSL with mine fine. The only main issue I've heard about is people that aren't using alphanumeric passwords, but as you've noted you clearly do. Not sure...

**Comment by Marcel40625** [comment]
thanks!

**Comment by aerouk** [comment]
Setup guide was updated to take this into account.
