### ISSUE TITLE
e-415 fix?

### ISSUE THREAD

**Issue by Arilis** [aerouk/imageserve#53]
I have my settings all correct. my regex is fine. My config is fine. But i get error e-415.

**Comment by aerouk** [comment]
Is your webserver set up to accept files? Users have experienced this error when the `upload_max_filesize` option is set too low in php.ini

**Comment by smaltin-rules** [comment]
I keep recieving e-415. My current php init has:
`upload_max_filesize = 1024M`
`post_max_size = 1024M`
I feel like I'm making a dumb mistake.

**Comment by aerouk** [comment]
Closing as this seems abandoned. If somehow this still doesn't work please reopen.
