### ISSUE TITLE
No Renaming?

### ISSUE THREAD

**Issue by Marcel40625** [aerouk/imageserve#56]
Hey there, is there a easy way for not renaming the files that got uploaded, i mean my share x already apply a timestamp, so there should be no dublicates possible, and i want to sort the images after.

**Comment by aerouk** [comment]
Hi,

There's no easy way to manage images at the moment. I may come back to this
at some point but it's not a priority for me at the moment.

Thanks.

**Comment by Marcel40625** [comment]
okay thanks anyway, very nice little tool ...
