### ISSUE TITLE
uploads redirect to homepage/index.html

### ISSUE THREAD

**Issue by johncena98** [aerouk/imageserve#58]
upon upload, sharex does seemingly nothing and the preview when clicked directs me to my urls initial webpage, there is no error when i test it, my config and destination settings are in line with setup, and I have written my permissions recursively (albeit on many folders, perhaps this is my issue) i would really love some help with this, i will post a video.

https://streamable.com/nks7t

**Comment by aerouk** [comment]
That video was an adventure 😂 Try using the regex `[^,]*$` instead of `[^,]^$` and let me know if it fixes your issue

**Comment by johncena98** [comment]
ok , now my files upload, but sharex does not redirect to the appropriate url, it just redirects me to my site url.
