### ISSUE TITLE
Weird url returned

### ISSUE THREAD

**Issue by JustLeader69420** [aerouk/imageserve#66]
Everything works fine, the screenshot gets uploaded and everything BUT it gives me a weird url, it gives back the entire path to the file on the hosting... How would I fix that?

**Comment by JustLeader69420** [comment]
https://shit-by.justleader.eu/images/png/t5My9.png
That's what it gives me, I can still take the bit out but it's annoying

**Comment by JustLeader69420** [comment]
um also while I'm at it, how would I make a Discord embed for this?

**Comment by JustLeader69420** [comment]
Okay figured the embed out

**Comment by JustLeader69420** [comment]
Figured out the path, I made a custom regex, (([a-z,0-9,A-Z][a-z,0-9,A-Z][a-z,0-9,A-Z][a-z,0-9,A-Z][a-z,0-9,A-Z])\.(gif|jpeg|png|webm))     I think you could make it so much easier but I just made a few screenshots and saw what characters it's making so I put that in a thing and I put in the formats that are in the folders, hope it will work, but now I don't know how I would integrate discord embeds, how would I get the image that's being pulled up in viewer.php? https://shit-by.justleader.eu/wXvtB.png

**Comment by aerouk** [comment]
It's probably giving you the super long argument because you have the
RAW_IMAGE_LINK config option enabled. Also, Discord embeds should just work
if you have RAW_IMAGE enabled. I never got round to adding support for
other cases like Twitter embeds because the script hasn't been updated in a
few years.

**Comment by JustLeader69420** [comment]
Yeah, well, when I enable raw image link, it's just the image, I am just linking to the screenshot, I made an embed in the viewer.phtml, if anyone that looks over this wants, put this and edit the urls and the title, the color and you have a nice embed for yourself :)
`<html>
  <head>
    <meta content="Shit By JustLeader" property="og:title">
    <meta content="<?php echo "$file.$type"; ?> &middot;>" property="og:description">
    <meta content="https://shit-by.JustLeader.eu/<?php echo "$file"; ?>" property="og:url">
    <meta content="https://shit-by.justleader.eu/images/<?php echo "$type"; ?>/<?php echo "$file.$type"; ?>" property="og:image">
    <meta name="twitter:card" content="summary_large_image">
    <meta content="#FF6600" data-react-helmet="true" name="theme-color">
  </head>
</html>
`

**Comment by JustLeader69420** [comment]
It's all now working so I'll close this
