### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by I-am-Myxi** [aerouk/imageserve#67]
![image](https://user-images.githubusercontent.com/80150167/112749704-bf9bbb80-8fe1-11eb-9a90-8e603d33a2cb.png)

**Comment by I-am-Myxi** [comment]
![image](https://user-images.githubusercontent.com/80150167/112749742-07224780-8fe2-11eb-9b16-ddb953a2127f.png)

**Comment by aerouk** [comment]
I saw you created another issue using nginx, but this one seems like an issue with the hosting provider you're using intercepting requests rather than an issue with the script.
