### ISSUE TITLE
Viewer Not Showing Up

### ISSUE THREAD

**Issue by LOLERN5** [aerouk/imageserve#68]
I have raw image disabled in the config but it won't show the viewer on the images page, please help!

**Comment by LOLERN5** [comment]
Fixed ( I had to add the viewer.php thing to the sharex config ) but how can i hide the viewer.php in the link?

**Comment by aerouk** [comment]
Navigating to /viewer.php is exactly the same as navigating to /

Your browser/web server may be caching the image it had saved before, so
clear your cache and try again.
