### ISSUE TITLE
ShareX updated Regex

### ISSUE THREAD

**Issue by dakisback2** [aerouk/imageserve#72]
Hi,

This is no longer working 

https://github.com/aerouk/imageserve/wiki/Setup

"$regex:1$" no longer returns a value and I'm unsure how to parse it properly.

Here's the new regex syntax: https://getsharex.com/docs/custom-uploader

**Comment by Ratedd** [comment]
https://github.com/aerouk/imageserve/issues/71#issuecomment-1181225451
