### ISSUE TITLE
Custom uploader tutorial for ShareX obsolete

### ISSUE THREAD

**Issue by jendrush** [aerouk/imageserve#73]
With the newly rewritten regex parser custom uploader in ShareX , the ShareX tutorial has become obsolete. At the same time, the ShareX update making these changes caused a malfunction - ShareX does not correctly parse the hash generated by the Upload script to create the screenshot url correctly.

**Comment by Ratedd** [comment]
https://github.com/aerouk/imageserve/issues/71#issuecomment-1181225451

**Comment by jendrush** [comment]
Thank You. You might consider updating the tutorial, along with leaving the previous one with a note in which version the change occurred.
