### ISSUE TITLE
gif upload doesn't work

### ISSUE THREAD

**Issue by addles** [aerouk/imageserve#9]
My GIF uploads don't work although the rest of the files will, upload all the code is the same on the upload.php file (besides the save destination).  It seems to return a 401 error (wrong password but its right passkey). 
![error 401](https://prtscr.io/uploads/png/YDIfi.png)

**Comment by aerouk** [comment]
@addles My theory on this is that the gif image is too large and the server isn't even reading the passkey in the POST data. Try uploading a smaller gif and see if the problem persists.

**Comment by addles** [comment]
yup never restarted apache

**Comment by aerouk** [comment]
@addles so is this issue resolved, or?
